export const FETCH_ALL_RECLAMATIONS = 'FETCH_ALL_RECLAMATIONS'; // naming the action with a verb that will make it more readable
export const FETCH_ALL_RECLAMATIONS_SUCCESS = 'FETCH_ALL_RECLAMATIONS_SUCCESS';
export const FETCH_ALL_RECLAMATIONS_FAIL = 'FETCH_ALL_RECLAMATIONS_FAIL';

export const FETCH_RECLAMATION_DETAILS = 'FETCH_RECLAMATION_DETAILS';
export const FETCH_RECLAMATION_DETAILS_SUCCESS = 'FETCH_RECLAMATION_DETAILS_SUCCESS';
export const FETCH_RECLAMATION_DETAILS_FAIL = 'FETCH_RECLAMATION_DETAILS_FAIL';

export const ADD_RECLAMATION = 'ADD_RECLAMATION';
export const ADD_RECLAMATION_SUCCESS = 'ADD_RECLAMATION_SUCCESS';
export const ADD_RECLAMATION_FAIL = 'ADD_RECLAMATION_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
